import React from 'react';
import { Card, Table, Tag, Typography, Button } from 'antd';
import { Sparkles, AlertCircle, ArrowRight } from 'lucide-react';

const { Title, Text } = Typography;

const RecommendationsTable = ({ recommendations = [], loading = false }) => {
  const columns = [
    {
      title: 'AI Insight',
      dataIndex: 'title',
      key: 'title',
      render: (text, record) => (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
          <strong style={{ color: 'var(--text-primary)', fontSize: 14 }}>{text}</strong>
          <Text type="secondary" style={{ fontSize: 13 }}>{record.description}</Text>
        </div>
      ),
    },
    {
      title: 'Module',
      dataIndex: 'category',
      key: 'category',
      width: 100,
      render: (category) => {
        const color = category === 'GEO' ? 'cyan' : category === 'AEO' ? 'purple' : 'blue';
        return <Tag color={color} style={{ borderRadius: 12, fontWeight: 600 }}>{category}</Tag>;
      },
    },
    {
      title: 'Type',
      dataIndex: 'type',
      key: 'type',
      width: 160,
      render: (type) => <Tag style={{ borderRadius: 12, background: 'transparent', border: '1px solid var(--border-color)', color: 'var(--text-secondary)' }}>{type}</Tag>,
    },
    {
      title: 'Action',
      key: 'action',
      width: 120,
      render: () => (
        <Button type="link" style={{ color: 'var(--accent-secondary)', fontWeight: 600, padding: 0, display: 'flex', alignItems: 'center', gap: 4 }}>
          Fix Now <ArrowRight size={14} />
        </Button>
      ),
    },
  ];

  return (
    <Card 
      title={
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, paddingTop: 8 }}>
          <Sparkles size={20} color="var(--accent-secondary)" />
          <Title level={5} style={{ margin: 0, fontSize: 18, fontWeight: 700, color: 'var(--text-primary)' }}>AI Recommendations</Title>
        </div>
      }
      className="glassmorphism" 
      style={{ borderRadius: 16, border: '1px solid var(--border-color)', boxShadow: 'var(--shadow-sm)' }} 
      bodyStyle={{ padding: '0px' }}
    >
      <div style={{ padding: '16px 24px', borderBottom: '1px solid var(--border-color)', background: 'rgba(59, 130, 246, 0.05)', display: 'flex', alignItems: 'flex-start', gap: 12 }}>
        <AlertCircle size={18} color="var(--accent-info)" style={{ marginTop: 2 }} />
        <Text style={{ fontSize: 14, color: 'var(--text-primary)' }}>
          These recommendations are generated by AI analyzing your content gaps against top-ranking entities and answer intents.
        </Text>
      </div>
      <Table 
        columns={columns} 
        dataSource={recommendations} 
        rowKey={(record, index) => record._id || index}
        pagination={{ pageSize: 5 }} 
        loading={loading}
        size="middle"
        style={{ margin: 0 }}
      />
    </Card>
  );
};

export default RecommendationsTable;
